configfile: "../config/config-glicid-scratch.yml"

#SAMPLES = ["ALL_t_variable"]
SAMPLES = ["4T1_S+_5000HVG","4T1_S-_5000HVG"]
NPATTERNS = config["nPatternsRange"]
reportqmd = config["reportqmd"]

rule all:
    input:
        # Markers Excel
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers.xlsx",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers_seurat.xlsx",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        # Contributions
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_genes.txt",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),
        # Pattern specificity PDF
        expand(
            [
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_patterns.png",
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_metagroups.png",
            ],
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),
        expand(
            [
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",
            ],
	        sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            [
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/enrichment/{sample}.npatterns-{npatterns}.c2_enrichment.csv",
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/overrep/{sample}.npatterns-{npatterns}.c2_overrepresentation.csv",
            ],
	        sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            [
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/enrichment/{sample}.npatterns-{npatterns}.c8_enrichment.csv",
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/overrep/{sample}.npatterns-{npatterns}.c8_overrepresentation.csv",
            ],
	        sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            [
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",
            ],
	    sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
    [
        config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_unique.png",
        config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_unique.png",
    ],
    sample=SAMPLES,
    npatterns=NPATTERNS
),

        expand(
            [
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.pdf",
                config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.pdf",
            ],
	    sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        # Kruskal-Wallis results CSV
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.kw_results.csv",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        # Pairwise Wilcoxon results CSV
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.pairwise_results.csv",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/enrichment/{sample}.npatterns-{npatterns}.c2_enrichment_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/overrep/{sample}.npatterns-{npatterns}.c2_overrepresentation_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/enrichment/{sample}.npatterns-{npatterns}.c8_enrichment_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/overrep/{sample}.npatterns-{npatterns}.c8_overrepresentation_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_{dataset}.png",
            sample=SAMPLES,
            npatterns=NPATTERNS,
            dataset=["nmf"]
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/infos/{sample}.npatterns-{npatterns}.nb_cells.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/signatures/{sample}.npatterns-{npatterns}.signature.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.dotplot.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.dotplot_seurat.png",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/coo/{sample}.npatterns-{npatterns}.nmf.umap-coords.txt",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_{dataset}.png",
            sample=SAMPLES,
            npatterns=NPATTERNS,
            dataset=["nmf"]
        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_meta_{dataset}.png",
            sample=SAMPLES,
            npatterns=NPATTERNS,
            dataset=["nmf"]
        ),

#        expand(
#            [
#                config["mayaOutDir"] + "/{sample}/maya/heatmap_cluster_cols_rows.png",
#                config["mayaOutDir"] + "/{sample}/maya/heatmap_cluster_rows_only.png",
#                config["mayaOutDir"] + "/{sample}/maya/umap_clone_annotation.png",
#                config["mayaOutDir"] + "/{sample}/maya/ALL_modules_top_contrib_genes.pdf",
#                config["mayaOutDir"] + "/{sample}/maya/ALL_modules_specificity.pdf"
#            ],
#            sample=SAMPLES
#        ),

        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_recap_global.csv",
            sample=SAMPLES,
            npatterns=NPATTERNS
        ),
        expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/report/{sample}.npatterns-{npatterns}.report.html",
            sample=SAMPLES,
            npatterns=NPATTERNS
        )
rule cogaps:
    input:
        tumor_rna_seuratobj = config["dataDir"] + "/{sample}.seurat-object.rds"
    output:
        cogaps_rds = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    log:
        "logs/{sample}/{sample}-{npatterns}.log"
    benchmark:
        "benchmarks/{sample}/{sample}-{npatterns}.tsv"
    conda:
        "envs/cogaps.yml"
    threads: 80
    params:
        npatterns = "{npatterns}",
        nIterations = config["cogapsIterations"]
    script:
        "scripts/run_cogaps.R"


rule reduce_dim_cogaps:
    input:
        contrib_tsv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
    output:
        tsv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/coo/{sample}.npatterns-{npatterns}.nmf.umap-coords.txt",
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/reduce_dim.R"


rule pattern_markers:
    input:
        cogaps_rds = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        excel=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers.xlsx"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/run_pattern_markers.R"

rule pattern_markers_seurat:
    input:
        seurat_rds = config["dataDir"] + "/{sample}.seurat-object.rds",
        contrib_tsv = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt"
    output:
        excel = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers_seurat.xlsx"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/run_pattern_markers_seurat.R"

rule cells_contribution:
    input:
        cogaps_rds = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        tsv = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/cells_contribution.R"

rule genes_contribution:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        tsv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_genes.txt"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/genes_contribution.R"

rule patterns_specificity:
    input:
        contributions = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        meta  = config["metadataDir"]+ "/meta_subset.tsv"
    output:
        png1=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_patterns.png",
        png2=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_metagroups.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/patterns_specificity.R"

rule generate_hallmarks:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",
    conda:
        "envs/cogaps.yml"    
    threads: 1
    script:
        "scripts/generate_hallmarks.R"

rule generate_curated_gs:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/enrichment/{sample}.npatterns-{npatterns}.c2_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/overrep/{sample}.npatterns-{npatterns}.c2_overrepresentation.csv",
    conda:
        "envs/cogaps.yml"    
    threads: 1
    script:
        "scripts/generate_curated_gs.R"

rule generate_c8:
    input:
        cogaps_rds=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds"
    output:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/enrichment/{sample}.npatterns-{npatterns}.c8_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/overrep/{sample}.npatterns-{npatterns}.c8_overrepresentation.csv",
    conda:
        "envs/cogaps.yml"    
    threads: 1
    script:
        "scripts/generate_c8.R"        

rule generate_hallmarks_manually:
    input:
        contrib_txt=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_genes.txt",
    output:
        gsea_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        ora_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/generate_hallmarks_manually.R"

rule plot_hallmarks:
    input:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        pdf_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.pdf",
        pdf_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.pdf"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_hallmarks.R"

rule plot_uniq_hallmarks:
    input:
        csv_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        png_enrich=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_unique.png",
        png_overr=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_unique.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_uniq_hallmarks.R"

rule go_enrichment:
    input:
        markers=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/{sample}.npatterns-{npatterns}.markers.xlsx"
    output:
        pdf=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/{sample}.npatterns-{npatterns}.GO_enrichment.pdf"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/go_enrichment.R"


rule patterns_significance:
    input:
        contributions_file=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
    output:
        kw_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.kw_results.csv",
        pairwise_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.pairwise_results.csv"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/patterns_significance.R"


rule plot_markers:
    input:
        contrib = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        tumor_rna_seuratobj = config["dataDir"] + "/{sample}.seurat-object.rds",
        markers_excel = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers.xlsx"
    output:
        png=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.dotplot.png"
    conda:
        "envs/cogaps.yml" 
    threads: 1
    script:
        "scripts/plot_markers.R"


rule plot_markers_seurat:
    input:
        contrib = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        tumor_rna_seuratobj = config["dataDir"] + "/{sample}.seurat-object.rds",
        markers_excel = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers_seurat.xlsx"
    output:
        png=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.dotplot_seurat.png"
    conda:
        "envs/cogaps.yml" 
    threads: 1
    script:
        "scripts/plot_markers_seurat.R"

rule plot_hallmarks_heatmap:
    input:
        csv_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr  = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        png_heatmap_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_heatmap_overr  = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_hallmarks_heatmap.R"
  

rule plot_c2_heatmap:
    input:
        csv_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/enrichment/{sample}.npatterns-{npatterns}.c2_enrichment.csv",
        csv_overr  = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/overrep/{sample}.npatterns-{npatterns}.c2_overrepresentation.csv"
    output:
        png_heatmap_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/enrichment/{sample}.npatterns-{npatterns}.c2_enrichment_heatmap.png",
        png_heatmap_overr  = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c2/get_function/overrep/{sample}.npatterns-{npatterns}.c2_overrepresentation_heatmap.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_c2_heatmap.R"

rule plot_c8_heatmap:
    input:
        csv_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/enrichment/{sample}.npatterns-{npatterns}.c8_enrichment.csv",
        csv_overr  = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/overrep/{sample}.npatterns-{npatterns}.c8_overrepresentation.csv"
    output:
        png_heatmap_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/enrichment/{sample}.npatterns-{npatterns}.c8_enrichment_heatmap.png",
        png_heatmap_overr  = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/c8/get_function/overrep/{sample}.npatterns-{npatterns}.c8_overrepresentation_heatmap.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_c8_heatmap.R"

rule plot_hallmarks_heatmap_manually:
    input:
        csv_enrich =  config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        csv_overr =  config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv"
    output:
        png_heatmap_enrich = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_heatmap_overr = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_hallmarks_heatmap_manually.R"

rule umap_dominant:
    input:
        contributions=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        umap=lambda wildcards:
            f"{config['cogapsOutDir']}/{wildcards.sample}/cogaps/patterns_{wildcards.npatterns}/umap/coo/{wildcards.sample}.npatterns-{wildcards.npatterns}.nmf.umap-coords.txt"
    output:
        png=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_{dataset}.png"
    params:
        dataset="{dataset}"
    wildcard_constraints:
        dataset="nmf"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/plot_umap_dominant.R"

rule umap_weight:
    input:
        contributions = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        umap = lambda wildcards:
            f"{config['cogapsOutDir']}/{wildcards.sample}/cogaps/patterns_{wildcards.npatterns}/umap/coo/{wildcards.sample}.npatterns-{wildcards.npatterns}.nmf.umap-coords.txt"
    output:
        png = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_{dataset}.png"
    params:
        dataset = "{dataset}"
    wildcard_constraints:
        dataset = "nmf"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/plot_umap_weight.R"

rule umap_metadata:
    input:
        metadata  = config["metadataDir"]+ "/meta_subset.tsv",
        umap = lambda wildcards:
            f"{config['cogapsOutDir']}/{wildcards.sample}/cogaps/patterns_{wildcards.npatterns}/umap/coo/{wildcards.sample}.npatterns-{wildcards.npatterns}.nmf.umap-coords.txt"
    output:
        png = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_meta_{dataset}.png"
    params:
        dataset = "{dataset}"
    wildcard_constraints:
        dataset = "nmf"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/plot_umap_metadata.R"

rule nb_cells:
    input:
        contrib = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        metadata  = config["metadataDir"]+ "/meta_subset.tsv",
    output:
        png = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/infos/{sample}.npatterns-{npatterns}.nb_cells.png",
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/plot_nb_cells.R"


rule calculate_signature:
    input:
        contrib = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        tumor_rna_seuratobj = config["dataDir"] + "/{sample}.seurat-object.rds",
        signature = config["signatureDir"] + "/ALL_t_variable.npatterns-3.markers.xlsx",
        coo = config['cogapsOutDir']+"/{sample}/cogaps/patterns_{npatterns}/umap/coo/{sample}.npatterns-{npatterns}.nmf.umap-coords.txt"
    output:
        png = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/signatures/{sample}.npatterns-{npatterns}.signature.png"
    conda:
        "envs/cogaps.yml"
    script:
        "scripts/calculate_signature.R"
    

rule pathway_activity_maya:
    input:
        seurat = config["dataDir"] + "/{sample}.seurat-object.rds",
        metadata  = config["metadataDir"]+ "/meta_subset.tsv",
    output:
        heatmap1 = config["mayaOutDir"] + "/{sample}/maya/heatmap_cluster_cols_rows.png",
        heatmap2 = config["mayaOutDir"] + "/{sample}/maya/heatmap_cluster_rows_only.png",
        umap = config["mayaOutDir"] + "/{sample}/maya/umap_clone_annotation.png",
        top_genes = config["mayaOutDir"] + "/{sample}/maya/ALL_modules_top_contrib_genes.pdf",
        specificity = config["mayaOutDir"] + "/{sample}/maya/ALL_modules_specificity.pdf"
    conda:
        "envs/maya.yml"
    threads: 1
    script:
        "scripts/pathway_activity_maya.R"


rule recap_patterns_global:
    input:
        cogaps_files = expand(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/object/{sample}.npatterns-{npatterns}.cogaps-object.Rds",
            sample=SAMPLES,
            npatterns=NPATTERNS
        )
    output:
        csv = config["cogapsOutDir"] + "/{sample}/cogaps/patterns_recap_global.csv"
    conda:
        "envs/cogaps.yml"
    threads: 1
    script:
        "scripts/recap_patterns_global.R"


rule render_report:
    input:
        qmd=reportqmd,
        contrib_cells=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_cells.txt",
        contrib_genes=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/contributions/{sample}.npatterns-{npatterns}.contributions_genes.txt",
        markers_excel=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.markers.xlsx",
        dotplot=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/markers/{sample}.npatterns-{npatterns}.dotplot.png",

        enrich_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment.csv",
        overr_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation.csv",

        kw_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.kw_results.csv",
        pairwise_csv=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/statistics/{sample}.npatterns-{npatterns}.pairwise_results.csv",

        png_specificity_patterns=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_patterns.png",
        png_specificity_metagroups=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/specificity/{sample}.npatterns-{npatterns}.plot_metagroups.png",

        png_enrich_unique=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_unique.png",
        png_overr_unique=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_unique.png",

        png_enrich_heatmap=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_overr_heatmap=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/get_function/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png",

        png_enrich_heatmap_manually=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/enrichment/{sample}.npatterns-{npatterns}.hallmarks_enrichment_heatmap.png",
        png_overr_heatmap_manually=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/hallmarks/manually/overrep/{sample}.npatterns-{npatterns}.hallmarks_overrepresentation_heatmap.png",

        umap_nmf=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/{sample}.npatterns-{npatterns}.UMAP_dominant_nmf.png",

        umap_nb_cells=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/dominant/infos/{sample}.npatterns-{npatterns}.nb_cells.png",

        weight_nmf=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/umap/weight/{sample}.npatterns-{npatterns}.UMAP_weight_nmf.png",

        benchmark_tsv="benchmarks/{sample}/{sample}-{npatterns}.tsv"

    output:
        html=report(
            config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/report/{sample}.npatterns-{npatterns}.report.html",
            category="{sample}",            # ← un onglet par sample
            subcategory="CoGAPS Report",
            labels={"patterns": "{npatterns}"}
        )

    params:
        outdir=config["cogapsOutDir"] + "/{sample}/cogaps/patterns_{npatterns}/report",
        sample="{sample}",
        npatterns="{npatterns}"

    log:
        "logs/{sample}/{sample}-{npatterns}.render_report.log"

    conda:
        "envs/quarto.yml"

    threads: 1

    shell:
        r"""
        mkdir -p "$(dirname "{log}")"
        LOGFILE=$(realpath "{log}")
        mkdir -p "{params.outdir}"

        export TMPDIR="${{TMPDIR:-/tmp}}"
        export DENO_DIR="$TMPDIR/quarto-deno-cache-{wildcards.sample}-{wildcards.npatterns}"
        export XDG_CACHE_HOME="$TMPDIR/quarto-xdg-cache-{wildcards.sample}-{wildcards.npatterns}"

        cp "{input.qmd}" "{params.outdir}/report_cogaps.qmd"
        cd "{params.outdir}"

        quarto render report_cogaps.qmd \
            --output "{params.sample}.npatterns-{params.npatterns}.report.html" \
            -P sample:"{params.sample}" \
            -P npatterns:"{params.npatterns}" \
            -P outdir:"{params.outdir}" \
            -P contrib_cells:"{input.contrib_cells}" \
            -P contrib_genes:"{input.contrib_genes}" \
            -P markers_excel:"{input.markers_excel}" \
            -P dotplot:"{input.dotplot}" \
            -P enrich_csv:"{input.enrich_csv}" \
            -P overr_csv:"{input.overr_csv}" \
            -P kw_csv:"{input.kw_csv}" \
            -P pairwise_csv:"{input.pairwise_csv}" \
            -P png_specificity_patterns:"{input.png_specificity_patterns}" \
            -P png_specificity_metagroups:"{input.png_specificity_metagroups}" \
            -P png_enrich_unique:"{input.png_enrich_unique}" \
            -P png_overr_unique:"{input.png_overr_unique}" \
            -P png_enrich_heatmap:"{input.png_enrich_heatmap}" \
            -P png_overr_heatmap:"{input.png_overr_heatmap}" \
            -P png_enrich_heatmap_manually:"{input.png_enrich_heatmap_manually}" \
            -P png_overr_heatmap_manually:"{input.png_overr_heatmap_manually}" \
            -P umap_nmf:"{input.umap_nmf}" \
            -P umap_nb_cells:"{input.umap_nb_cells}" \
            -P weight_nmf:"{input.weight_nmf}" \
            -P benchmark_tsv:"{input.benchmark_tsv}" \
            > "$LOGFILE" 2>&1
        """
 